MODULE INV_TRANS_CTL_MOD

  IMPLICIT NONE

  INTERFACE
    SUBROUTINE CUDA_DGEMM_GROUPED(&
        & BLAS_ID, CTA, CTB,      &
        & M, N, K,                &
        & ALPHA,                  &
        & A, LDA, OFFSETA,        &
        & B, LDB, OFFSETB,        &
        & BETA,                   &
        & C, LDC, OFFSETC,        &
        & BATCHCOUNT, STREAM, ALLOC&
    &) BIND(C, NAME='blas_dgemm_wrapper_grouped')
        USE ISO_C_BINDING
        INTEGER(C_INT), VALUE :: BLAS_ID, CTA, CTB, M, N(:), K(:), LDA, LDB, LDC, OFFSETA(:), OFFSETB(:), OFFSETC(:), BATCHCOUNT
        REAL(C_DOUBLE), VALUE  :: ALPHA,BETA
        REAL(C_DOUBLE)         :: A(*), B(*), C(*)
#ifdef _CUDA
      ATTRIBUTES(DEVICE) :: A,B,C
#endif
        INTEGER(KIND=c_size_t) :: STREAM
        TYPE(C_PTR), INTENT(IN), VALUE :: ALLOC
    END SUBROUTINE CUDA_DGEMM_GROUPED
  END INTERFACE

CONTAINS
  SUBROUTINE INV_TRANS_CTL(KF_UV_G,KF_SCALARS_G,KF_GP,KF_FS,KF_OUT_LT,&
    & KF_UV,KF_SCALARS,KF_SCDERS,&
    & PSPVOR,PSPDIV,PSPSCALAR,KVSETUV,KVSETSC,PGP,FSPGL_PROC,&
    & PSPSC3A,PSPSC3B,PSPSC2,KVSETSC3A,KVSETSC3B,KVSETSC2,PGPUV,PGP3A,PGP3B,PGP2)

    USE PARKIND_ECTRANS  ,ONLY : JPIM     ,JPRB,   JPRBT, JPRD

    USE CUDA_GEMM_BATCHED_MOD
    USE GROWING_ALLOCATOR_MOD

    IMPLICIT NONE

    INTEGER(KIND=JPIM), INTENT(IN) :: KF_UV_G
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_SCALARS_G
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_GP
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_FS
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_OUT_LT
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_UV
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_SCALARS
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_SCDERS
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPVOR(:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPDIV(:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPSCALAR(:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPSC3A(:,:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPSC3B(:,:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPSC2(:,:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETUV(:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETSC(:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETSC3A(:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETSC3B(:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETSC2(:)
    REAL(KIND=JPRB) ,OPTIONAL   ,INTENT(OUT) :: PGP(:,:,:)
    EXTERNAL  FSPGL_PROC
    OPTIONAL  FSPGL_PROC
    REAL(KIND=JPRB),OPTIONAL    ,INTENT(OUT) :: PGPUV(:,:,:,:)
    REAL(KIND=JPRB),OPTIONAL    ,INTENT(OUT) :: PGP3A(:,:,:,:)
    REAL(KIND=JPRB),OPTIONAL    ,INTENT(OUT) :: PGP3B(:,:,:,:)
    REAL(KIND=JPRB),OPTIONAL    ,INTENT(OUT) :: PGP2(:,:,:)

    INTEGER :: NS1 (2), KS1 (2)
    REAL*8 :: ZINP1 (2), ZAA1 (1,1,1), ZOUTA1 (2)
    INTEGER(KIND=JPIM)  :: IIN_STRIDES0, IOUT_STRIDES0, AOFFSETS1 (2), BOFFSETS1 (2), COFFSETS1 (2)
    TYPE(GROWING_ALLOCATION_TYPE), POINTER :: PTR1


    CALL CUDA_DGEMM_GROUPED_OVERLOAD1( &
        & 11, & ! unique identifier
        & CUBLAS_OP_N, CUBLAS_OP_T, &
        & 2, NS1(:), KS1(:), &
        & 1.0_8, &
        & ZINP1, IIN_STRIDES0, AOFFSETS1, &
        & ZAA1, SIZE(ZAA1,1), BOFFSETS1, &
        & 0.0_8, &
        & ZOUTA1, IOUT_STRIDES0, COFFSETS1, &
        & 2, STREAM=1_C_LONG, ALLOC=PTR1)

  END SUBROUTINE INV_TRANS_CTL

  SUBROUTINE CUDA_DGEMM_GROUPED_OVERLOAD1( &
      & BLAS_ID, TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, OFFSETA, &
      & BARRAY, LDB, OFFSETB, &
      & BETA, &
      & CARRAY, LDC, OFFSETC, &
      & BATCHCOUNT, STREAM, ALLOC)
    USE GROWING_ALLOCATOR_MOD
    USE ISO_C_BINDING
    USE PARKIND_ECTRANS  ,ONLY : JPIM     ,JPRB,   JPRBT, JPRD
    USE OPENACC, ONLY: ACC_GET_CUDA_STREAM
    INTEGER(KIND=C_INT), INTENT(IN) :: BLAS_ID
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSA
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSB
    INTEGER(KIND=JPIM) :: M
    INTEGER(KIND=JPIM) :: N(:)
    INTEGER(KIND=JPIM) :: K(:)
    REAL(KIND=JPRD) :: ALPHA
    REAL(KIND=JPRD), DIMENSION(:) :: AARRAY
    INTEGER(KIND=JPIM) :: LDA
    INTEGER(KIND=JPIM) :: OFFSETA(:)
    REAL(KIND=JPRD), DIMENSION(*) :: BARRAY
    INTEGER(KIND=JPIM) :: LDB
    INTEGER(KIND=JPIM) :: OFFSETB(:)
    REAL(KIND=JPRD) :: BETA
    REAL(KIND=JPRD), DIMENSION(:) :: CARRAY
    INTEGER(KIND=JPIM) :: LDC
    INTEGER(KIND=JPIM) :: OFFSETC(:)
    INTEGER(KIND=JPIM) :: BATCHCOUNT
    INTEGER(KIND=C_LONG) :: STREAM
    TYPE(GROWING_ALLOCATION_TYPE), INTENT(IN) :: ALLOC

    !$ACC HOST_DATA USE_DEVICE(AARRAY,BARRAY,CARRAY)
    CALL CUDA_DGEMM_GROUPED( &
      & BLAS_ID, TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, OFFSETA, &
      & BARRAY, LDB, OFFSETB, &
      & BETA, &
      & CARRAY, LDC, OFFSETC, &
      & BATCHCOUNT, ACC_GET_CUDA_STREAM(STREAM), C_LOC(ALLOC))
    !$ACC END HOST_DATA
  END SUBROUTINE CUDA_DGEMM_GROUPED_OVERLOAD1

END MODULE INV_TRANS_CTL_MOD
